# main.py
# -----------------------------------------------------
# This is the main entry point for the AI data analyst application.
# It orchestrates the workflow of generating code based on user requests, executing that code, and reflecting on any errors that occur during execution.
# The workflow is built using a state graph, which defines the different states (nodes) of the agent and the transitions (edges) between those states based on the outcomes of each step.
# The agent starts by generating code based on the user's request and the data summary.
# It then attempts to execute the generated code. If the execution is successful, the workflow ends. 
# If there is an error, the agent reflects on the error and generates a new version of the code, which is then executed again.
# This loop continues until the code executes successfully or a maximum number of iterations is reached, at which point the workflow ends to prevent infinite loops.
# ------------------------------------------------------


# =================================================
# Importing the Necessary Libraries
# --------------------------------------------
# TypedDict from typing is used to define a structured state for the agent, ensuring that all necessary information is organized and easily accessible throghout the workflow.
# StateGraph from langgraph is the core of our workflow orchestration, allowing us to define nodes for code generation, execution, and reflection, as well as the edges that connect these nodes based on the outcomes of each step.
# OllamaLLM from langchain_ollama is the interface to our language model, which we use to generate code and reflect on errors based on the prompts defined in prompts.py.
# GENERATOR_PROMPT and REFLECTION_PROMPT from prompts.py are the templates that guide the LLM in generating code and reflecting on errors, ensuring that the outputs are structured and relevant to the task at hand.
# execute_python_code from tools.py is the function that safely executes the generated Python code, capturing any output or errors that occur during execution, which is crucial for the reflection step.
# pandas is imported to ensure that any code generated by the LLM that uses pandas for data analysis can be executed without issues, as it's one of the allowed libraries in our environment.
# =================================================
from typing import TypedDict
from langgraph.graph import StateGraph, END
from langchain_ollama import OllamaLLM
from prompts import GENERATOR_PROMPT, REFLECTION_PROMPT
from tools import execute_python_code
import pandas as pd


# =================================================
# Defining the Agent State
# --------------------------------------------
# AgentState is a TypedDict that defines the structure of the state that will be passed through the workflow.
# It includes the user's request, the file name of the data, a summary of the data, the generated code, any errors that occur, and the number of iterations the agent has gone through.
# This structured state allows us to keep track of all relevant information as the agent generates code, executes it, and reflects on any errors, ensuring that the workflow can make informed decisions at each step.
# =================================================
class AgentState(TypedDict):
    request: str
    file_name: str
    data_summary: str
    code: str
    error: str
    iterations: int

llm = OllamaLLM(model="qwen2.5-coder:7b", temperature=0.0)
MAX_ITERATIONS = 3


# =================================================
# generate_code_node is the function that generates Python code based on the user's request and the data summary using the GENERATOR_PROMPT.
# It checks if the output starts with "CLARIFICATION_NEEDED:", which indicates that the LLM is asking for more information from the user. If this is the case, it returns a state with an error of "CLARIFICATION" to pause the workflow and wait for user input.
# If the output is valid code, it returns the generated code and increments the iteration count.
# =================================================
def generate_code_node(state: AgentState):
    print("Agent: Thinking...")
    prompt = GENERATOR_PROMPT.format(
        user_request=state['request'],
        file_name=state['file_name'],
        data_summary=state['data_summary']
    )
    output = llm.invoke(prompt)
    
    if output.startswith("CLARIFICATION_NEEDED:"):
        print(f"Agent paused: {output}")
        return {"code": output, "error": "CLARIFICATION", "iterations": state.get("iterations", 0) + 1}
        
    return {"code": output, "iterations": state.get("iterations", 0) + 1}


# =================================================
# execute_node is the function that takes the generated code from the state and attempts to execute it using the execute_python_code function from tools.py.
# It captures the result of the execution, and if it's successful, it returns the output. 
# If there is an error, it returns the error message to be used in the reflection step.
# =================================================
def execute_node(state: AgentState):
    print("System: Executing code...")
    result = execute_python_code(state['code'])
    
    if result["status"] == "success":
        print(f"Success! Output:\n{result['output']}")
        return {"error": None}
    else:
        print(f"Error Caught! Passing back to agent...")
        return {"error": result["output"]}


# =================================================
# reflect_node is the function that takes the error from the previous execution attempt and uses the REFLECTION_PROMPT to generate a new version of the code that attempts to fix the error.
# It returns the new code and increments the iteration count, allowing the workflow to attempt execution again with the corrected code.
# =================================================
def reflect_node(state: AgentState):
    print("Agent: Analyzing error and rewriting code...")
    prompt = REFLECTION_PROMPT.format(code=state['code'], error=state['error'])
    new_code = llm.invoke(prompt)
    return {"code": new_code, "iterations": state['iterations'] + 1}


# =================================================
# route_execution is a function that determines the next step in the workflow after attempting to execute the code.
# If the error is "CLARIFICATION", it means the agent is waiting for user input, so the workflow ends to allow for that.
# If there is no error, it means the code executed successfully, so the workflow also ends.
# If the number of iterations has reached the maximum allowed, it ends the workflow to prevent infinite loops.
# Otherwise, it routes back to the "reflect" node to allow the agent to analyze the error and generate a new version of the code to try executing again.
# =================================================
def route_execution(state: AgentState):
    if state["error"] == "CLARIFICATION":
        return END
    elif state["error"] is None:
        return END 
    elif state["iterations"] >= MAX_ITERATIONS:
        print("Reached max loops.")
        return END
    else:
        return "reflect"

# Build the Graph
workflow = StateGraph(AgentState)
workflow.add_node("generate", generate_code_node)
workflow.add_node("execute", execute_node)
workflow.add_node("reflect", reflect_node)

workflow.set_entry_point("generate")
workflow.add_edge("generate", "execute")
workflow.add_conditional_edges("execute", route_execution)
workflow.add_edge("reflect", "execute")

agent_app = workflow.compile()