# streamlit_app.py
# ------------------------------------------------------
# This is the Streamlit application that serves as the user interface for the AI data analyst.
# It allows users to upload their datasets, view the extracted schema, and interact with the agent through a chat interface.
# The application handles file uploads, displays the data summary, and manages the chat interactions where users can ask questions about their data.
# When a user submits a query, the application invokes the agent workflow defined in main.py, passing the user's request and the data summary to generate, execute, and reflect on the Python code needed to answer the query.
# The application also handles the display of results, including any charts generated by the agent. 
# Also provides feedback on the execution process, such as the number of iterations required to correct any errors in the code.
# ------------------------------------------------------


# =================================================
# Importing the Necessary Libraries
# --------------------------------------------
# streamlit is the framework used to build the web application, providing components for file uploads, chat interfaces, and displaying results.
# pandas is used to read the uploaded Excel or CSV files and extract the schema information, which is then passed to the agent for code generation.
# os is used to handle file operations, such as saving the uploaded file and managing the output directory for generated charts.
# agent_app is the main workflow defined in main.py that orchestrates the code generation, execution, and reflection process of the AI data analyst.
# =================================================
import streamlit as st
import pandas as pd
import os
from main import agent_app


# Environment Preparation
os.makedirs("output", exist_ok=True)
st.set_page_config(page_title="Agentic Data Scientist", page_icon="🤖", layout="wide")
st.title("🤖 Self-Correcting Data Analyst")
st.markdown("Upload an Excel file and ask me to analyze it. I will write, test, and correct my own code to give you the answer.")

# File Upload Mechanism
uploaded_file = st.file_uploader("Upload your dataset (.xlsx or .csv)", type=["xlsx", "csv"])

if uploaded_file is not None:
    file_name = uploaded_file.name
    with open(file_name, "wb") as f:
        f.write(uploaded_file.getbuffer())
    
    # Extract Schema
    try:
        if file_name.endswith('.csv'):
            df = pd.read_csv(file_name)
        else:
            df = pd.read_excel(file_name)
            
        st.success(f"File '{file_name}' loaded successfully! ({df.shape[0]} rows, {df.shape[1]} columns)")
        schema_info = f"Columns: {list(df.columns)}\n\nData Types:\n{df.dtypes.to_string()}\n\nSample Data (First 2 rows):\n{df.head(2).to_markdown()}"
        
        with st.expander("View Extracted File Schema"):
            st.text(schema_info)

        # Chat Interface
        user_query = st.chat_input("E.g., 'What is the average sales by region?' or 'Plot sales over time'")
        
        if user_query:
            with st.chat_message("user"):
                st.write(user_query)
                
            with st.chat_message("assistant"):
                with st.spinner("Agent is thinking, writing, and testing code locally..."):
                    
                    initial_state = {
                        "request": user_query, 
                        "file_name": file_name,
                        "data_summary": schema_info,
                        "code": "", 
                        "error": "", 
                        "output": "",
                        "iterations": 0
                    }
                    
                    final_state = agent_app.invoke(initial_state)
                    
                    if final_state["error"] == "CLARIFICATION":
                        st.warning(final_state["code"])
                    else:
                        st.write("**Execution Complete**")
                        
                        if final_state.get("output"):
                            st.info(f"**Result:**\n\n{final_state['output']}")

                        with st.expander("View Final Executed Code"):
                            st.code(final_state["code"], language="python")
                            st.write(f"Loops required to fix errors: {final_state['iterations'] - 1}")
                        
                        png_files = [f for f in os.listdir("output") if f.endswith('.png')]

                        if png_files:
                            image_name = png_files[0]
                            image_path = os.path.join("output", image_name)
        
                            chart_display_title = image_name.replace('.png', '').replace('_', ' ').title()
                            st.subheader(chart_display_title)
                            st.image(image_path)
                            
                            os.remove(image_path)

    except Exception as e:
        st.error(f"Error reading file: {e}")